#!/bin/bash
echo "START : "`date` >> /tmp/log_gmic_update_server
cd $HOME/work/src/gmic/ && git pull
cd $HOME/work/src/gmic-community/ && git pull
gmic $HOME/work/src/resources.gmic $HOME/work/src/gmic/src/gmic_stdlib.gmic update_server > /tmp/gui_filters.txt
if [ ! -f /tmp/gui_filters.old ]; then
    cp -f /tmp/gui_filters.txt /tmp/gui_filters.old;
fi

GMIC_LOGIN=`gmic -v - echo_stdout[] \$\{\"gmic_ftp 0\"\} q`
GMIC_PASSWD=`gmic -v - echo_stdout[] \$\{\"gmic_ftp 1\"\} q`
GMIC_FTP=ftp.cluster011.hosting.ovh.net
lftp ftp://$GMIC_LOGIN:$GMIC_PASSWD@$GMIC_FTP -e "put -O /www/gmic/ /tmp/gui_filters.txt; quit"

git diff /tmp/gui_filters.old /tmp/gui_filters.txt > /tmp/gui_filters.diff
diff=`cat /tmp/gui_filters.diff | wc -l`
if [ $diff -gt 10 ]; then
    lftp ftp://$GMIC_LOGIN:$GMIC_PASSWD@$GMIC_FTP -e "put -O /www/gmic/ /tmp/gui_filters.diff; quit"
#    wget -O /tmp/sendmail.php http://gmic.eu/sendmail.php >/dev/null
fi
cp -f /tmp/gui_filters.txt /tmp/gui_filters.old
echo "END : "`date` >> /tmp/log_gmic_update_server
echo " " >> /tmp/log_gmic_update_server
notify-send -i face-smile "G'MIC Filter Update" "Done!"
